### ISSUE TITLE
Can't run the run.py file even after installing the dependencies required.(Windows)

### ISSUE THREAD

**Issue by Fire-Hound** [openai/large-scale-curiosity#14]
Hi,
I wanted to try out the model but I'm getting this OS error of module not found. Can you help me figure out what the problem might be?
I have Mujocu, baselines, mpi4py, opencv, tensorflow and opengl installed.

`(gym) C:\Users\Vikram\Desktop\NeuralNets\large-scale-curiosity>python "c:\Users\Vikram\Desktop\NeuralNets\large-scale-curiosity\run.py"
C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\gym\envs\registration.py:14: PkgResourcesDeprecationWarning: Parameters to load are deprecated.  Call .resolve and .require separately.
  result = entry_point.load(False)
Traceback (most recent call last):
  File "c:\Users\Vikram\Desktop\NeuralNets\large-scale-curiosity\run.py", line 211, in <module>
    start_experiment(**args.__dict__)
  File "c:\Users\Vikram\Desktop\NeuralNets\large-scale-curiosity\run.py", line 31, in start_experiment
    envs_per_process=args['envs_per_process'])
  File "c:\Users\Vikram\Desktop\NeuralNets\large-scale-curiosity\run.py", line 45, in __init__
    self._set_env_vars()
  File "c:\Users\Vikram\Desktop\NeuralNets\large-scale-curiosity\run.py", line 102, in _set_env_vars
    env = self.make_env(0, add_monitor=False)
  File "c:\Users\Vikram\Desktop\NeuralNets\large-scale-curiosity\run.py", line 123, in make_env_all_params
    env = gym.make(args['env'])
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\gym\envs\registration.py", line 167, in make
    return registry.make(id)
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\gym\envs\registration.py", line 119, in make
    env = spec.make()
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\gym\envs\registration.py", line 85, in make
    cls = load(self._entry_point)
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\gym\envs\registration.py", line 14, in load
    result = entry_point.load(False)
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\pkg_resources\__init__.py", line 2346, in load
    return self.resolve()
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\pkg_resources\__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\gym\envs\atari\__init__.py", line 1, in <module>
    from gym.envs.atari.atari_env import AtariEnv
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\gym\envs\atari\atari_env.py", line 9, in <module>
    import atari_py
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\atari_py\__init__.py", line 1, in <module>
    from .ale_python_interface import *
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\site-packages\atari_py\ale_python_interface.py", line 29, in <module>
    ale_lib = cdll.LoadLibrary(get_shared_lib_path())
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\ctypes\__init__.py", line 426, in LoadLibrary
    return self._dlltype(name)
  File "C:\Users\Vikram\Anaconda3\envs\gym\lib\ctypes\__init__.py", line 348, in __init__
    self._handle = _dlopen(self._name, mode)
**OSError: [WinError 126] The specified module could not be found`**

**Comment by jinyeom** [comment]
Looks to me that you may have not installed `atari-py`. It is not officially supported on Windows, but this wonderful person made a Windows port of it (https://stackoverflow.com/questions/42605769/openai-gym-atari-on-windows)!

Try after installing it as followed:

```bash
pip install --no-index -f https://github.com/Kojoley/atari-py/releases atari_py
```

**Comment by Fire-Hound** [comment]
Sorry to reply so late. I appreciate you took time to answer this.

I have the atari_py installed. 
`(gym) C:\Users\Vikram\Desktop\NeuralNets\large-scale-curiosity>pip install --no-index -f https://github.com/Kojoley/atari-py/releases atari_py`
**`Requirement already satisfied: atari_py in c:\users\vikram\anaconda3\envs\gym\lib\site-packages (0.1.7)
Requirement already satisfied: numpy in c:\users\vikram\anaconda3\envs\gym\lib\site-packages (from atari_py) (1.16.0)
Requirement already satisfied: six in c:\users\vikram\anaconda3\envs\gym\lib\site-packages (from atari_py) (1.12.0)
`**
I still have the same problem while running the run.py file.

**Comment by Cospui** [comment]
I have the same problem too.
